
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace lisaandtj.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Guest
{

    public int Id { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public int Guests { get; set; }

    public bool Attending { get; set; }

    public string Message { get; set; }

    public System.DateTime DateStamp { get; set; }

    public bool Deleted { get; set; }

    public string Shuttle { get; set; }

}

}
