//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lisaandtj.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string UserName { get; set; }
        public int Votes { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime LastVote { get; set; }
    }
}
